# Generated by Django 2.1.3 on 2019-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Название', max_length=100)),
                ('longitude', models.FloatField(default='Долгота', max_length=100)),
                ('latitude', models.FloatField(default='Широта', max_length=100)),
            ],
        ),
    ]
