# Generated by Django 2.1.3 on 2019-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190414_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Название', max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
